---
services:
  wallabag:
    image: wallabag/wallabag
    restart: unless-stopped
    networks:
      - traefik
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
      - SYMFONY__ENV__DATABASE_DRIVER=pdo_mysql
      - SYMFONY__ENV__DATABASE_HOST=db
      - SYMFONY__ENV__DATABASE_PORT=3306
      - SYMFONY__ENV__DATABASE_NAME=wallabag
      - SYMFONY__ENV__DATABASE_USER=wallabag
      - SYMFONY__ENV__DATABASE_PASSWORD=wallapass
      - SYMFONY__ENV__DATABASE_CHARSET=utf8mb4
      - SYMFONY__ENV__DATABASE_TABLE_PREFIX="wallabag_"
      - SYMFONY__ENV__MAILER_DSN=smtp://127.0.0.1
      - SYMFONY__ENV__FROM_EMAIL=attinagaoxu@gmail.com
      - SYMFONY__ENV__DOMAIN_NAME=https://wallabag.attina.io
      - SYMFONY__ENV__SERVER_NAME="wallabag"
    volumes:
      - /data/attina.io/wallabag/images:/var/www/wallabag/web/assets/images
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wallabag.rule=Host(`wallabag.attina.io`)"
      - "traefik.http.routers.wallabag.tls=true"

    depends_on:
      - db
      - redis
  db:
    image: mariadb
    restart: unless-stopped
    networks:
      - traefik
    environment:
      - MYSQL_ROOT_PASSWORD=wallaroot
    volumes:
      - /data/attina.io/wallabag/data:/var/lib/mysql
  redis:
    image: redis:alpine
    restart: unless-stopped    
    networks:
      - traefik

networks:
  traefik:
    external: true