services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    ports:
      - 9080:8080
    volumes:
      - /data/attina.io/StirlingPDF/trainingData:/usr/share/tessdata # Required for extra OCR languages
      - /data/attina.io/StirlingPDF/extraConfigs:/configs
      - /data/attina.io/StirlingPDF/customFiles:/customFiles/
      - /data/attina.io/StirlingPDF/logs:/logs/
      - /data/attina.io/StirlingPDF/pipeline:/pipeline/
    environment:
      - DISABLE_ADDITIONAL_FEATURES=false
      - LANGS=en_GB
    networks:
      - traefik
    restart: unless-stopped
    labels:
      - traefik.enable=true
      - traefik.http.routers.stirlingpdf.rule=Host(`stirlingpdf.attina.io`)
#      - traefik.http.routers.stirlingpdf.service=stirlingpdf
      - traefik.http.routers.stirlingpdf.tls=true
#      - traefik.http.services.stirlingpdf.loadbalancer.server.port=9080

networks:
  traefik:
    external: true
