services:

  # main service
  talebook:
    restart: unless-stopped
    image: talebook/talebook
    volumes:
      - /data/attina.io/talebook:/data
    networks:
      - traefik
    labels:
      - traefik.enable=true
      - traefik.http.routers.talebook.rule=Host(`talebook.attina.io`)
      - traefik.http.routers.talebook.tls=true
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      # 调整为『SSR=ON』可开启「服务器端渲染」模式，对于搜索引擎更友好，同时更消耗服务器性能
      - SSR=OFF
    depends_on:
      - douban-rs-api

  # optional, for meta plugins
  # please set "http://douban-rs-api" in settings
  douban-rs-api:
    restart: unless-stopped
    image: ghcr.io/cxfksword/douban-api-rs

networks:
  traefik:
    external: true