global:
  checkNewVersion: true
  sendAnonymousUsage: false

api:
  insecure: true
  dashboard: true
  debug: false
  disableDashboardAd: true

entryPoints:
  http:
    address: ":80"                            # Create the HTTP entrypoint on port 80
  https:
    address: ":443"                           # Create the HTTPS entrypoint on port 443

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false

  file:
    filename: /etc/traefik/dynamic.yml
    watch: true
