---
services:
  calibre-web:
    image: lscr.io/linuxserver/calibre-web:latest
    container_name: calibre-web
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
      - DOCKER_MODS=linuxserver/mods:universal-calibre #optional
      - OAUTHLIB_RELAX_TOKEN_SCOPE=1 #optional
    volumes:
      - /data/attina.io/calibre-web/data:/config
      - /data/attina.io/calibre-web/calibre/library:/books
    networks:
      - traefik
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # Http
      - "traefik.http.routers.calibre-web.rule=Host(`calibre.attina.io`)"
      - "traefik.http.routers.calibre-web.entrypoints=http"
      - "traefik.http.middlewares.calibre-web-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.calibre-web.middlewares=calibre-web-https-redirect"
      # Https
      - "traefik.http.routers.calibre-web-secure.entrypoints=https"
      - "traefik.http.routers.calibre-web-secure.rule=Host(`calibre.attina.io`)"
      - "traefik.http.routers.calibre-web-secure.tls=true"
      - "traefik.http.routers.calibre-web-secure.service=calibre-web"
      # Service
      - "traefik.http.services.calibre-web.loadbalancer.server.port=8083"
      - "traefik.http.services.calibre-web.loadbalancer.server.scheme=http"

networks:
  traefik:
    external: true