---
#---------------------------------------------------------------------#
#     Homarr - A simple, yet powerful dashboard for your server.     #
#---------------------------------------------------------------------#
services:
  homarr:
    container_name: homarr
    image: ghcr.io/homarr-labs/homarr:latest
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /data/attina.io/homarr/appdata:/appdata
    environment:
      - SECRET_ENCRYPTION_KEY=b346165247b05de297666e045f6e5e6f124adf5ee818aa2c0c32ed6d16becbb3
    ports:
      - 7575:7575
    labels:
      - traefik.enable=true
      - traefik.http.routers.homarr.rule=Host(`homarr.attina.io`)
      - traefik.http.routers.homarr.tls=true

networks:
  traefik:
    external: true