---
services:
  broker:
    image: docker.io/library/redis:7
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - redisdata:/data
  db:
    image: docker.io/library/postgres:15
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - /data/attina.io/paperless-ngx/database:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
  webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    restart: unless-stopped
    networks:
      - traefik
    depends_on:
      - db
      - broker
      - gotenberg
      - tika
    labels:
      - traefik.enable=true
      - traefik.http.routers.paperless.rule=Host(`paperless.attina.io`)
      - traefik.http.routers.paperless.tls=true
    volumes:
      - /data/attina.io/paperless-ngx/data:/usr/src/paperless/data
      - /data/attina.io/paperless-ngx/media:/usr/src/paperless/media
      - /data/attina.io/paperless-ngx/export:/usr/src/paperless/export
      - /data/attina.io/paperless-ngx/consume:/usr/src/paperless/consume
    env_file: stack.env
    environment:
      PAPERLESS_REDIS: redis://broker:6379
      PAPERLESS_DBHOST: db
      PAPERLESS_TIKA_ENABLED: 1
      PAPERLESS_TIKA_GOTENBERG_ENDPOINT: http://gotenberg:3000
      PAPERLESS_TIKA_ENDPOINT: http://tika:9998
      # other settings ...
      # PAPERLESS_OCR_USER_ARGS: '{"invalidate_digital_signatures": true}'
      PAPERLESS_OCR_USER_ARGS: '{"continue_on_soft_render_error": true}'
  gotenberg:
    image: docker.io/gotenberg/gotenberg:7.10
    restart: unless-stopped
    networks:
      - traefik
    # The gotenberg chromium route is used to convert .eml files. We do not
    # want to allow external content like tracking pixels or even javascript.
    command:
      - gotenberg
      - --chromium-disable-javascript=true
      - --chromium-allow-list=file:///tmp/.*

  tika:
    image: docker.io/apache/tika:latest
    restart: unless-stopped
    networks:
      - traefik

volumes:
  redisdata:

networks:
  traefik:
    external: true