---
services:
  peppermint_postgres:
    container_name: peppermint_postgres
    image: postgres:latest
    restart: always
    networks:
      - traefik
    volumes:
      - /data/attina.io/peepermint/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: peppermint
      POSTGRES_DB: peppermint

  peppermint:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    restart: always
    networks:
      - traefik
    depends_on:
      - peppermint_postgres
    environment:
      DB_USERNAME: "peppermint"
      DB_PASSWORD: "peppermint"
      DB_HOST: "peppermint_postgres"
      SECRET: 'peppermint4life'
      API_URL: "https://peppermintapi.attina.io"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=traefik"
      # http
      - "traefik.http.routers.pepermint.rule=Host(`pepermint.attina.io`)"
      - "traefik.http.routers.pepermint.entrypoints=http"
      - "traefik.http.middlewares.pepermint-https-redirect.redirectscheme.scheme=https"
      - "traefik.http.routers.pepermint.middlewares=pepermint-https-redirect"
      # https
      - "traefik.http.routers.pepermint-secure.rule=Host(`pepermint.attina.io`)"
      - "traefik.http.routers.pepermint-secure.entrypoints=https"
      - "traefik.http.routers.pepermint-secure.tls=true"
      - "traefik.http.routers.pepermint-secure.service=pepermint"
      # Service
      - "traefik.http.services.pepermint.loadbalancer.server.port=3000"
      - "traefik.http.services.pepermint.loadbalancer.server.scheme=http"

networks:
  traefik:
    external: true