---
services:
  peppermint_postgres:
    container_name: peppermint_postgres
    image: postgres:latest
    restart: unless-stopped
    networks:
      - traefik
    volumes:
      - /data/attina.io/peepermint/pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: peppermint
      POSTGRES_PASSWORD: peppermint
      POSTGRES_DB: peppermint

  peppermint:
    container_name: peppermint
    image: pepperlabs/peppermint:latest
    restart: unless-stopped
    networks:
      - traefik
    depends_on:
      - peppermint_postgres
    environment:
      DB_USERNAME: "peppermint"
      DB_PASSWORD: "peppermint"
      DB_HOST: "peppermint_postgres"
      SECRET: 'peppermint4life'
      API_URL: "https://peppermintapi.attina.io"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    labels:
      - traefik.enable=true
      - traefik.http.routers.pepermint.rule=Host(`pepermint.attina.io`)
      - traefik.http.routers.pepermint.tls=true
      - traefik.http.routers.pepermint.service=pepermint
      - traefik.http.services.pepermint.loadbalancer.server.port=3000

networks:
  traefik:
    external: true